/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdministrativeUnit {
  'unitType' : string,
  'parentState' : [] | [string],
  'name' : string,
  'parentConstituency' : [] | [string],
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Constituency {
  'mp' : [] | [Representative],
  'mlas' : Array<Representative>,
  'name' : string,
}
export interface Directory {
  'states' : Array<State>,
  'unionTerritories' : Array<State>,
  'administrativeUnits' : Array<AdministrativeUnit>,
  'primeMinister' : [] | [Representative],
}
export interface Feedback {
  'id' : string,
  'status' : string,
  'contactInfo' : string,
  'admin' : [] | [Principal],
  'type' : string,
  'message' : string,
  'response' : [] | [string],
  'timestamp' : bigint,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface LocalCivicBody {
  'photoPath' : [] | [string],
  'representativeName' : string,
  'bodyName' : string,
  'bodyType' : string,
}
export interface LogoHistory {
  'admin' : Principal,
  'logoData' : string,
  'timestamp' : bigint,
}
export interface NgoNpo {
  'id' : string,
  'organizationName' : string,
  'missionStatement' : string,
  'principal' : Principal,
  'impactScore' : bigint,
  'contactPerson' : string,
  'description' : string,
  'approvalTimestamp' : [] | [bigint],
  'email' : string,
  'website' : string,
  'logoPath' : string,
  'approved' : boolean,
  'address' : string,
  'rejectionNote' : [] | [string],
  'phone' : string,
  'registrationDate' : bigint,
  'showContactInfo' : boolean,
}
export interface PendingProfileEdit {
  'id' : string,
  'status' : string,
  'submittedAt' : bigint,
  'volunteerId' : string,
  'updates' : VolunteerProfileUpdate,
  'rejectionNote' : [] | [string],
  'volunteerPrincipal' : Principal,
}
export interface Report {
  'id' : string,
  'status' : string,
  'issueType' : string,
  'photoPath' : string,
  'username' : [] | [string],
  'resolvedByVolunteer' : boolean,
  'mpData' : [] | [Representative],
  'reporterName' : [] | [string],
  'customAddress' : [] | [string],
  'cmPhotoPath' : [] | [string],
  'mlaDesignation' : string,
  'submittedByVolunteer' : boolean,
  'state' : string,
  'cmData' : [] | [Representative],
  'cmName' : [] | [string],
  'address' : string,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'pmData' : [] | [Representative],
  'localCivicBody' : [] | [LocalCivicBody],
  'pmName' : [] | [string],
  'location' : { 'latitude' : number, 'longitude' : number },
  'mlaPhotoPath' : [] | [string],
  'proofPhotoPath' : [] | [string],
  'pmPhotoPath' : [] | [string],
  'mlaName' : [] | [string],
  'coordinates' : string,
  'completionNotes' : [] | [string],
}
export interface Representative {
  'politicalParty' : [] | [string],
  'photoPath' : string,
  'name' : string,
  'lastUpdated' : bigint,
  'email' : string,
  'twitterHandle' : string,
  'remarks' : string,
}
export interface RoadmapFeature {
  'id' : string,
  'title' : string,
  'icon' : string,
  'description' : string,
  'progress' : bigint,
  'sectionId' : string,
  'timestamp' : bigint,
}
export interface State {
  'cm' : [] | [Representative],
  'constituencies' : Array<Constituency>,
  'name' : string,
  'isUnionTerritory' : boolean,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : string,
  'photoPath' : string,
  'principal' : Principal,
  'contactInfo' : string,
  'impactScore' : bigint,
  'name' : string,
  'approvalTimestamp' : [] | [bigint],
  'approved' : boolean,
  'address' : string,
  'rejectionNote' : [] | [string],
  'showFullMobile' : boolean,
  'applicationDate' : bigint,
}
export interface VolunteerProfileUpdate {
  'photoPath' : string,
  'contactInfo' : string,
  'name' : string,
  'address' : string,
  'showFullMobile' : boolean,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addAdministrativeUnit' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    undefined
  >,
  'addConstituency' : ActorMethod<[string, string], undefined>,
  'addMlaToConstituency' : ActorMethod<
    [string, string, Representative],
    undefined
  >,
  'addMpToConstituency' : ActorMethod<
    [string, string, Representative],
    undefined
  >,
  'addState' : ActorMethod<[string, [] | [Representative], boolean], undefined>,
  'addUnionTerritory' : ActorMethod<[string, [] | [Representative]], undefined>,
  'applyVolunteer' : ActorMethod<
    [string, string, string, string, boolean],
    string
  >,
  'approveNgoNpo' : ActorMethod<[string], undefined>,
  'approveVolunteer' : ActorMethod<[string], undefined>,
  'approveVolunteerProfileEdit' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFeature' : ActorMethod<[string, RoadmapFeature], undefined>,
  'deleteConstituency' : ActorMethod<[string, string], undefined>,
  'deleteFeature' : ActorMethod<[string], undefined>,
  'deleteFeedback' : ActorMethod<[string], undefined>,
  'deleteReport' : ActorMethod<[string], undefined>,
  'deleteRepresentative' : ActorMethod<[string, string, string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'exportDirectory' : ActorMethod<[], Directory>,
  'getAdminDirectory' : ActorMethod<[], Directory>,
  'getAdministrativeUnits' : ActorMethod<[], Array<AdministrativeUnit>>,
  'getAdmins' : ActorMethod<[], Array<Principal>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllNgoNpos' : ActorMethod<[], Array<NgoNpo>>,
  'getAllPendingProfileEdits' : ActorMethod<[], Array<PendingProfileEdit>>,
  'getAllReports' : ActorMethod<[], Array<Report>>,
  'getAllRepresentatives' : ActorMethod<[], Array<Representative>>,
  'getAllVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConstituenciesByState' : ActorMethod<[string], Array<Constituency>>,
  'getConstituency' : ActorMethod<[string, string], [] | [Constituency]>,
  'getCurrentLogo' : ActorMethod<[], string>,
  'getDirectory' : ActorMethod<[], Directory>,
  'getDirectoryWithPhotos' : ActorMethod<[], Directory>,
  'getFeedbackByContactInfo' : ActorMethod<[string], Array<Feedback>>,
  'getFeedbackById' : ActorMethod<[string], [] | [Feedback]>,
  'getFeedbackByStatus' : ActorMethod<[string], Array<Feedback>>,
  'getFeedbackByType' : ActorMethod<[string], Array<Feedback>>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getInitialReports' : ActorMethod<[], Array<Report>>,
  'getLogoHistory' : ActorMethod<[], Array<LogoHistory>>,
  'getMpByAreaOrBlock' : ActorMethod<[string], [] | [Representative]>,
  'getMpByConstituency' : ActorMethod<[string], [] | [Representative]>,
  'getMyNgoNpoProfile' : ActorMethod<[], [] | [NgoNpo]>,
  'getMyPendingProfileEdit' : ActorMethod<[], [] | [PendingProfileEdit]>,
  'getMyProfileEditHistory' : ActorMethod<[], Array<PendingProfileEdit>>,
  'getMyVolunteerProfile' : ActorMethod<[], [] | [Volunteer]>,
  'getNextReports' : ActorMethod<[bigint, bigint], Array<Report>>,
  'getNgoNpoById' : ActorMethod<[string], [] | [NgoNpo]>,
  'getNgoNpoDirectory' : ActorMethod<[], Array<NgoNpo>>,
  'getPaginatedReports' : ActorMethod<[bigint, bigint], Array<Report>>,
  'getPaginatedReportsOptimized' : ActorMethod<[bigint, bigint], Array<Report>>,
  'getRecentReports' : ActorMethod<[bigint], Array<Report>>,
  'getReport' : ActorMethod<[string], [] | [Report]>,
  'getReportsByState' : ActorMethod<[string], Array<Report>>,
  'getReportsForAdminTable' : ActorMethod<
    [],
    Array<[Report, string, string, string]>
  >,
  'getReportsWithAddressAndCoordinates' : ActorMethod<
    [],
    Array<[Report, string, string]>
  >,
  'getReportsWithAddresses' : ActorMethod<[], Array<[Report, string]>>,
  'getReportsWithCompleteLocationData' : ActorMethod<
    [],
    Array<
      [
        Report,
        { 'latitude' : number, 'longitude' : number },
        [] | [string],
        string,
        string,
      ]
    >
  >,
  'getReportsWithCustomAddresses' : ActorMethod<
    [],
    Array<[Report, [] | [string], string]>
  >,
  'getReportsWithFullLocationData' : ActorMethod<
    [],
    Array<
      [
        Report,
        { 'latitude' : number, 'longitude' : number },
        [] | [string],
        string,
        string,
      ]
    >
  >,
  'getReportsWithLocations' : ActorMethod<
    [],
    Array<[Report, { 'latitude' : number, 'longitude' : number }]>
  >,
  'getReportsWithLocationsAndAddresses' : ActorMethod<
    [],
    Array<
      [Report, { 'latitude' : number, 'longitude' : number }, string, string]
    >
  >,
  'getReportsWithLocationsAndAddressesOptimized' : ActorMethod<
    [],
    Array<
      [Report, { 'latitude' : number, 'longitude' : number }, string, string]
    >
  >,
  'getReportsWithMinisterPhotos' : ActorMethod<
    [],
    Array<[Report, [] | [string], [] | [string], [] | [string]]>
  >,
  'getReportsWithMinisterPhotosOptimized' : ActorMethod<
    [],
    Array<[Report, [] | [string], [] | [string], [] | [string]]>
  >,
  'getReportsWithPhotos' : ActorMethod<[], Array<[Report, string]>>,
  'getReportsWithPhotosOptimized' : ActorMethod<[], Array<[Report, string]>>,
  'getRoadmapFeatures' : ActorMethod<[], Array<RoadmapFeature>>,
  'getState' : ActorMethod<[string], [] | [State]>,
  'getTotalReportCount' : ActorMethod<[], bigint>,
  'getTotalUniqueVisitors' : ActorMethod<[], bigint>,
  'getUnionTerritory' : ActorMethod<[string], [] | [State]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], string>,
  'getVolunteerById' : ActorMethod<[string], [] | [Volunteer]>,
  'getVolunteerDirectory' : ActorMethod<[], Array<Volunteer>>,
  'importDirectory' : ActorMethod<[Directory], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'moveFeature' : ActorMethod<[string, string], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'registerNgoNpo' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    string
  >,
  'rejectNgoNpo' : ActorMethod<[string, string], undefined>,
  'rejectVolunteer' : ActorMethod<[string, string], undefined>,
  'rejectVolunteerProfileEdit' : ActorMethod<[string, string], undefined>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'respondToFeedback' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPrimeMinister' : ActorMethod<[Representative], undefined>,
  'submitFeedback' : ActorMethod<[string, string, string], string>,
  'submitReport' : ActorMethod<
    [
      string,
      number,
      number,
      [] | [string],
      [] | [string],
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      string,
      string,
      boolean,
      [] | [Representative],
      [] | [Representative],
      [] | [Representative],
      string,
      string,
      [] | [LocalCivicBody],
    ],
    string
  >,
  'submitVolunteerProfileEdit' : ActorMethod<
    [string, VolunteerProfileUpdate],
    string
  >,
  'trackUniqueVisitor' : ActorMethod<[], undefined>,
  'updateAdministrativeUnit' : ActorMethod<
    [string, AdministrativeUnit],
    undefined
  >,
  'updateConstituency' : ActorMethod<[string, string, Constituency], undefined>,
  'updateDirectory' : ActorMethod<[Directory], undefined>,
  'updateFeature' : ActorMethod<[string, RoadmapFeature], undefined>,
  'updateFeedbackStatus' : ActorMethod<[string, string], undefined>,
  'updateLocalCivicBody' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'updateNgoNpoPrivacy' : ActorMethod<[string, boolean], undefined>,
  'updateReport' : ActorMethod<[string, Report], undefined>,
  'updateReportAddress' : ActorMethod<[string, string], undefined>,
  'updateReportAddressAndCoordinates' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'updateReportAdminTable' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'updateReportCoordinates' : ActorMethod<[string, string], undefined>,
  'updateReportFullLocation' : ActorMethod<
    [string, number, number, [] | [string], string, string],
    undefined
  >,
  'updateReportLocation' : ActorMethod<[string, number, number], undefined>,
  'updateReportMinisterPhotos' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [string]],
    undefined
  >,
  'updateReportPhoto' : ActorMethod<[string, string], undefined>,
  'updateReportStatus' : ActorMethod<
    [string, string, string, string, [] | [string], boolean],
    boolean
  >,
  'updateRepresentative' : ActorMethod<
    [string, string, string, Representative],
    undefined
  >,
  'updateRepresentativeDetails' : ActorMethod<
    [string, string, string, string, Representative],
    undefined
  >,
  'updateState' : ActorMethod<[string, State], undefined>,
  'updateUnionTerritory' : ActorMethod<[string, State], undefined>,
  'updateVolunteerPrivacy' : ActorMethod<[string, boolean], undefined>,
  'uploadLogo' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];